export const pohApi_URL =
  "https://api.thegraph.com/subgraphs/name/kleros/proof-of-humanity-mainnet";
export const ipfs_BASEURL = "https://ipfs.io/";
export const initialChallengeDate = 1615334400;
export const filterArray = [
  "has",
  "as",
  "the",
  "is",
  "in",
  "this",
  "with",
  "submitter",
  "should",
  "be",
  "at",
  "and",
  "required",
  "are",
  "not",
  "of",
  "ethereum",
  "to",
  "that",
  "a",
  "does",
  "which",
  "profile",
  "registe",
  "by",
  "policy",
  "i",
  "submitted",
  "it",
  "must",
  "request",
  "submission",
  "eth",
  "least",
  "violates",
  "case",
  "registry",
  "for",
  "therefore",
  "incorrect",
  "than",
];
